### ISSUE TITLE
add descriptions (titles) to buttons

### ISSUE THREAD

**Issue by Andre601** [worldwidepixel/badger-legacy#2]
The icons used for these buttons aren't really as clear as they could be, so adding a description (i.e. in the form of a title attribute) could help in figuring out what each one does exactly.

![grafik](https://github.com/worldwidepixel/badger/assets/11576465/e7a9829c-3a0e-46cc-ae6d-ef505240d826)

**Comment by worldwidepixel** [comment]
What do you mean by a 'title attribute'? Do you mean a sort of popout?
![image](https://github.com/worldwidepixel/badger/assets/58098422/187082e1-529b-4ea3-8dc1-9545b4ee9aad)

**Comment by Andre601** [comment]
Yes

**Comment by worldwidepixel** [comment]
I'll see what I can do.

**Comment by worldwidepixel** [comment]
![image](https://github.com/worldwidepixel/badger/assets/58098422/d891b345-a113-40ea-9a16-4c5e48f79814)

Working on descriptions on-hover.

**Comment by worldwidepixel** [comment]
Badger 1.3.6 adds these tooltips. I'll close the issue. If there is a problem, please make another issue or ping me on Discord.

Thanks for the feedback!
